package systemGuis;

import domain.ConstructionsManagementSystem;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
    Davit Dostourian Erbe 281665 & Diego Pereira Puig - 329028
*/

public class ImportData extends javax.swing.JFrame {

    private ConstructionsManagementSystem system1;
    
    public ImportData(ConstructionsManagementSystem system) {
        system1 = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImportLabel = new javax.swing.JLabel();
        ImportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importacion de Datos");
        setMinimumSize(new java.awt.Dimension(286, 125));
        setPreferredSize(new java.awt.Dimension(305, 150));
        setResizable(false);
        getContentPane().setLayout(null);

        ImportLabel.setText("Importación de Datos para Obra Nueva");
        getContentPane().add(ImportLabel);
        ImportLabel.setBounds(30, 20, 220, 16);

        ImportButton.setText("Importar");
        ImportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportButtonMouseClicked(evt);
            }
        });
        ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ImportButton);
        ImportButton.setBounds(30, 60, 90, 23);

        setBounds(0, 0, 300, 113);
    }// </editor-fold>//GEN-END:initComponents

    private void ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportButtonActionPerformed
    if(system1.obtainOwners().isEmpty() || system1.obtainForemen().isEmpty()){
        System.out.println("There are no owners, or there are no foremen registered.");
        JOptionPane.showMessageDialog(null, "Registrar por lo menos 1 Capataz y 1 Propetario.", "Error: No propetarios o capataces", 0);
    }else{
        System.out.println("Foreman/ owners are there!");
        JFileChooser fileChooser = new JFileChooser();
            if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                String filename = fileChooser.getSelectedFile().getAbsolutePath();
                system1.importDataConstructionSite(filename);
            }
        }
    }//GEN-LAST:event_ImportButtonActionPerformed

    private void ImportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportButtonMouseClicked
        // BUTTON CLICKED CODE
    }//GEN-LAST:event_ImportButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportData(system1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImportButton;
    private javax.swing.JLabel ImportLabel;
    // End of variables declaration//GEN-END:variables
}
