package systemGuis;

import domain.*;
import javax.swing.JOptionPane;

public class RegisterForeman extends javax.swing.JFrame {
    
    private ConstructionsManagementSystem system1;

    public RegisterForeman(ConstructionsManagementSystem system) {
        system1 = system;
        initComponents();
    }
    
     private boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
     private boolean validateInputs(String name, String id, String address, String year) {
        if (name.length() < 3) {
            JOptionPane.showMessageDialog(null, 
                "El nombre debe tener al menos 3 caracteres.", 
                "Nombre inválido", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (!isNumeric(id)) {
            JOptionPane.showMessageDialog(null, 
                "La cédula de identidad debe contener solo números.", 
                "ID inválido", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
       
        if (address.length() < 4) {
            JOptionPane.showMessageDialog(null, 
                "La dirección debe tener al menos 4 caracteres.", 
                "Dirección inválida", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (!isNumeric(year) || Integer.parseInt(year) <= 0) {
            JOptionPane.showMessageDialog(null, 
                "El año debe ser un número positivo.", 
                "Año inválido", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterForemanTitle = new javax.swing.JLabel();
        foremanNameInput = new javax.swing.JTextField();
        NameForemanLable = new javax.swing.JLabel();
        IdForemanLable = new javax.swing.JLabel();
        foremanIdInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        foremanAddressInput = new javax.swing.JTextField();
        YearOfIncomeForeman = new javax.swing.JLabel();
        foremanYearInput = new javax.swing.JTextField();
        RemoveForemanButton = new javax.swing.JButton();
        AddForemanButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Capataz");
        setResizable(false);
        getContentPane().setLayout(null);

        RegisterForemanTitle.setText("Registrar Capataz");
        getContentPane().add(RegisterForemanTitle);
        RegisterForemanTitle.setBounds(16, 16, 110, 16);
        getContentPane().add(foremanNameInput);
        foremanNameInput.setBounds(20, 70, 150, 22);

        NameForemanLable.setText("Nombre:");
        getContentPane().add(NameForemanLable);
        NameForemanLable.setBounds(20, 50, 60, 16);

        IdForemanLable.setText("Cédula de Identidad:");
        getContentPane().add(IdForemanLable);
        IdForemanLable.setBounds(20, 110, 130, 16);
        getContentPane().add(foremanIdInput);
        foremanIdInput.setBounds(20, 130, 150, 22);

        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 50, 60, 16);

        foremanAddressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foremanAddressInputActionPerformed(evt);
            }
        });
        getContentPane().add(foremanAddressInput);
        foremanAddressInput.setBounds(200, 70, 160, 22);

        YearOfIncomeForeman.setText("Año de ingreso:");
        getContentPane().add(YearOfIncomeForeman);
        YearOfIncomeForeman.setBounds(200, 110, 100, 16);
        getContentPane().add(foremanYearInput);
        foremanYearInput.setBounds(200, 130, 160, 22);

        RemoveForemanButton.setText("Borrar");
        RemoveForemanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveForemanButtonMouseClicked(evt);
            }
        });
        RemoveForemanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveForemanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveForemanButton);
        RemoveForemanButton.setBounds(220, 180, 110, 23);

        AddForemanButton1.setText("Agregar");
        AddForemanButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddForemanButton1MouseClicked(evt);
            }
        });
        AddForemanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddForemanButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(AddForemanButton1);
        AddForemanButton1.setBounds(20, 180, 110, 23);

        setBounds(0, 0, 414, 257);
    }// </editor-fold>//GEN-END:initComponents

    private void foremanAddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foremanAddressInputActionPerformed
        //THIS IS EMPTY
    }//GEN-LAST:event_foremanAddressInputActionPerformed

    private void RemoveForemanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveForemanButtonActionPerformed
        //THIS IS EMPTY
    }//GEN-LAST:event_RemoveForemanButtonActionPerformed

    private void RemoveForemanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveForemanButtonMouseClicked
        String foremanName = foremanNameInput.getText().trim();
        String foremanId = foremanIdInput.getText().trim();
        String foremanAddress = foremanAddressInput.getText().trim();
        String foremanYearStr = foremanYearInput.getText().trim();
        
        if (foremanNameInput.getText().isBlank() || foremanIdInput.getText().isBlank() || foremanAddressInput.getText().isBlank() || foremanYearInput.getText().isBlank()){
            JOptionPane.showMessageDialog(null, 
                    "Debe completar todos los campos!", 
                    "Error!", 
                    JOptionPane.ERROR_MESSAGE);
        }else {
            //if  (validateInputs(foremanName,foremanId,foremanAddress,foremanYearStr)){
                int foremanYear = Integer.parseInt(foremanYearStr);
                if (system1.removeForeman(foremanName, foremanId, foremanAddress, foremanYear)){
                    // Clear the input fields
                    foremanNameInput.setText("");
                    foremanIdInput.setText("");
                    foremanAddressInput.setText("");
                    foremanYearInput.setText("");
                    JOptionPane.showMessageDialog(null, 
                        "Foreman borrado!", 
                        "Exito!", 
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                JOptionPane.showMessageDialog(null,
                    "No existe este foreman!",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                }
            //}
        }
    }//GEN-LAST:event_RemoveForemanButtonMouseClicked

    private void AddForemanButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddForemanButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddForemanButton1MouseClicked

    private void AddForemanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddForemanButton1ActionPerformed
        String foremanName = foremanNameInput.getText().trim();
        String foremanId = foremanIdInput.getText().trim();
        String foremanAddress = foremanAddressInput.getText().trim();
        String foremanYearStr = foremanYearInput.getText().trim();
        
        if (foremanNameInput.getText().isBlank() || foremanIdInput.getText().isBlank() || foremanAddressInput.getText().isBlank() || foremanYearInput.getText().isBlank()){
            JOptionPane.showMessageDialog(null, 
                    "Debe completar todos los campos!", 
                    "Error!", 
                    JOptionPane.ERROR_MESSAGE);
        }else {
            if  (validateInputs(foremanName,foremanId,foremanAddress,foremanYearStr)){
                int foremanYear = Integer.parseInt(foremanYearStr);
                if (system1.registerForeman(foremanName, foremanId, foremanAddress, foremanYear)){
                    // Clear the input fields
                    foremanNameInput.setText("");
                    foremanIdInput.setText("");
                    foremanAddressInput.setText("");
                    foremanYearInput.setText("");
                    JOptionPane.showMessageDialog(null, 
                        "Foreman guardado!", 
                        "Exito!", 
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                JOptionPane.showMessageDialog(null,
                    "Ya existe este foreman!",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_AddForemanButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForeman(system1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddForemanButton1;
    private javax.swing.JLabel IdForemanLable;
    private javax.swing.JLabel NameForemanLable;
    private javax.swing.JLabel RegisterForemanTitle;
    private javax.swing.JButton RemoveForemanButton;
    private javax.swing.JLabel YearOfIncomeForeman;
    private javax.swing.JTextField foremanAddressInput;
    private javax.swing.JTextField foremanIdInput;
    private javax.swing.JTextField foremanNameInput;
    private javax.swing.JTextField foremanYearInput;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
